<template>
  <div>
    <v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{ error }}</v-alert>

    <v-card border variant="flat" class="mb-5">
      <v-card-item>
        <v-card-title>Executable baseline validation</v-card-title>
        <v-card-subtitle>Structural checks and a one-case Prosimos smoke simulation</v-card-subtitle>
        <template #append>
          <v-btn
            color="primary"
            variant="tonal"
            prepend-icon="mdi-shield-sync-outline"
            :loading="validationRunning"
            @click="runValidation"
          >
            Validate baseline
          </v-btn>
        </template>
      </v-card-item>
      <v-card-text>
        <v-alert :type="validationAlertType" variant="tonal" density="compact">
          <strong>{{ validationLabel }}</strong>
          <span v-if="validationState?.report?.smoke_simulation?.status === 'passed'">
            · Prosimos smoke simulation passed for one case.
          </span>
          <div v-if="validationState?.report?.errors?.length" class="mt-2">
            <div v-for="message in validationState.report.errors" :key="message">• {{ message }}</div>
          </div>
          <div v-if="validationError" class="mt-2">{{ validationError }}</div>
        </v-alert>
      </v-card-text>
    </v-card>

    <div v-if="loading" class="text-center py-12">
      <v-progress-circular indeterminate color="primary" />
    </div>

    <v-card v-else-if="!available" border variant="flat">
      <v-card-item>
        <v-card-title>Parameter evidence is unavailable</v-card-title>
        <v-card-subtitle>AureaSim could not initialize candidates from this project's baseline.</v-card-subtitle>
      </v-card-item>
      <v-card-text>
        <v-alert type="warning" variant="tonal">
          The project needs a readable <code>AutoGenerated_Base_params.json</code> containing supported numeric parameters.
        </v-alert>
      </v-card-text>
    </v-card>

    <template v-else>
      <v-row class="mb-4">
        <v-col cols="12" md="8">
          <v-card border variant="flat" height="100%">
            <v-card-item>
              <v-card-title>Parameter evidence and review</v-card-title>
              <v-card-subtitle>
                Compare alternative values before selecting the executable configuration.
              </v-card-subtitle>
              <template #append>
                <div class="d-flex align-center" style="gap: 8px">
                  <v-btn
                    size="small"
                    color="primary"
                    variant="tonal"
                    prepend-icon="mdi-package-variant-closed-check"
                    :disabled="!activeCandidateIds.length || validationState?.status !== 'valid'"
                    @click="openHybridDialog"
                  >
                    Freeze selected configuration
                  </v-btn>
                  <v-chip
                    :color="auditChainValid ? 'success' : 'error'"
                    size="small"
                    variant="tonal"
                    :prepend-icon="auditChainValid ? 'mdi-shield-check' : 'mdi-shield-alert'"
                  >
                    {{ auditEventCount }} audited decision{{ auditEventCount === 1 ? '' : 's' }}
                  </v-chip>
                </div>
              </template>
            </v-card-item>
            <v-card-text>
              <div class="d-flex flex-wrap" style="gap: 8px">
                <v-chip size="small" variant="outlined">{{ candidates.length }} candidates</v-chip>
                <v-chip size="small" color="warning" variant="tonal">
                  {{ reviewQueue.length }} need attention
                </v-chip>
                <v-chip size="small" color="success" variant="tonal">
                  {{ statusCount('locked') }} locked
                </v-chip>
              </div>
            </v-card-text>
          </v-card>
        </v-col>
        <v-col cols="12" md="4">
          <v-card border variant="flat" height="100%">
            <v-card-item>
              <v-card-title>Review principle</v-card-title>
            </v-card-item>
            <v-card-text class="text-body-2 text-medium-emphasis">
              Expected error comes from previous evaluations of the method. Measured fidelity appears only when this exact value has an independent reference.
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <v-card v-if="reviewQueue.length" border variant="flat" class="mb-4">
        <v-card-item>
          <v-card-title class="text-subtitle-1">Weak-parameter review queue</v-card-title>
          <v-card-subtitle>Highest-risk unresolved assumptions appear first.</v-card-subtitle>
        </v-card-item>
        <v-card-text class="pt-0">
          <v-list density="compact" lines="two">
            <v-list-item v-for="item in reviewQueue" :key="item.candidate_id">
              <template #prepend>
                <v-avatar color="warning" variant="tonal" size="34">
                  <span class="text-caption font-weight-bold">{{ Math.round(item.priority_score) }}</span>
                </v-avatar>
              </template>
              <v-list-item-title>{{ item.entity_name || item.entity_id }}</v-list-item-title>
              <v-list-item-subtitle>{{ item.reasons.join(' · ') }}</v-list-item-subtitle>
            </v-list-item>
          </v-list>
        </v-card-text>
      </v-card>

      <div class="mb-3">
        <div class="text-h6">Candidate comparison</div>
        <div class="text-body-2 text-medium-emphasis">
          Alternatives are grouped by the exact baseline parameter they can replace.
        </div>
      </div>
      <v-card
        v-for="group in candidateGroups"
        :id="groupElementId(group.key)"
        :key="group.key"
        border
        variant="flat"
        class="mb-4"
        :style="focusedGroupKey === group.key ? { borderColor: 'rgb(var(--v-theme-primary))', borderWidth: '2px' } : undefined"
      >
        <v-card-item>
          <v-card-title class="text-subtitle-1">{{ group.entityName }}</v-card-title>
          <v-card-subtitle>{{ humanize(group.parameterFamily) }}</v-card-subtitle>
          <template #append>
            <v-chip v-if="group.candidates.some(isActive)" color="success" variant="tonal" size="small">
              Active candidate selected
            </v-chip>
          </template>
        </v-card-item>
        <v-card-text class="pa-0">
          <v-table density="comfortable">
            <thead>
              <tr>
                <th>Method</th>
                <th>Value</th>
                <th>Source</th>
                <th>Expected error</th>
                <th>Measured fidelity</th>
                <th>Status</th>
                <th class="text-right">Decision</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="candidate in group.candidates" :key="candidate.candidate_id">
                <td>
                  <v-chip size="x-small" variant="tonal">{{ humanize(candidate.method) }}</v-chip>
                  <div class="text-caption text-medium-emphasis mt-1">
                    {{ candidate.evidence?.length ?? 0 }} evidence record{{ candidate.evidence?.length === 1 ? '' : 's' }}
                    · revision {{ candidate.candidate_revision }}
                  </div>
                </td>
                <td class="text-body-2">{{ formatCandidateValue(candidate) }}</td>
                <td>
                  <div class="text-body-2 font-weight-medium">{{ evidenceSource(candidate) }}</div>
                  <div class="text-caption text-medium-emphasis mt-1">{{ evidenceSummary(candidate) }}</div>
                </td>
                <td>
                  <v-chip :color="confidenceColor(candidate.confidence_grade)" size="x-small" variant="tonal">
                    {{ candidate.confidence_grade }} evidence
                  </v-chip>
                  <div class="text-caption mt-1">{{ expectedErrorRange(candidate) }}</div>
                  <div class="text-caption text-medium-emphasis">{{ reliabilityContext(candidate) }}</div>
                </td>
                <td>
                  <div class="text-body-2">{{ measuredFidelity(candidate) }}</div>
                  <div v-if="candidate.measured_fidelity" class="text-caption text-medium-emphasis">
                    {{ fidelityReference(candidate) }}
                  </div>
                </td>
                <td>
                  <v-chip :color="statusColor(candidate.review_status)" size="x-small" variant="tonal">
                    {{ candidate.review_status }}
                  </v-chip>
                  <v-chip v-if="isActive(candidate)" color="success" size="x-small" class="ml-1">
                    active
                  </v-chip>
                </td>
                <td class="text-right text-no-wrap">
                  <v-btn
                    v-if="isExecutable(candidate)"
                    size="small"
                    :color="isActive(candidate) ? 'success' : 'primary'"
                    :variant="isActive(candidate) ? 'tonal' : 'flat'"
                    :disabled="isActive(candidate) || candidate.review_status === 'rejected'"
                    class="mr-1"
                    @click="openApplication(candidate)"
                  >
                    {{ isActive(candidate) ? 'In baseline' : 'Use in baseline' }}
                  </v-btn>
                  <v-tooltip v-else text="This measure is diagnostic evidence and cannot replace a Prosimos input.">
                    <template #activator="{ props: tooltipProps }">
                      <v-chip v-bind="tooltipProps" size="x-small" variant="outlined" class="mr-1">Diagnostic</v-chip>
                    </template>
                  </v-tooltip>
                  <v-menu :disabled="candidate.locked">
                    <template #activator="{ props: menuProps }">
                      <v-btn
                        v-bind="menuProps"
                        size="small"
                        variant="text"
                        :disabled="candidate.locked"
                        icon="mdi-dots-vertical"
                      />
                    </template>
                    <v-list density="compact">
                      <v-list-item title="Accept" prepend-icon="mdi-check" @click="openReview(candidate, 'accept')" />
                      <v-list-item title="Edit value" prepend-icon="mdi-pencil" @click="openReview(candidate, 'edit')" />
                      <v-list-item title="Reject" prepend-icon="mdi-close" @click="openReview(candidate, 'reject')" />
                      <v-list-item
                        title="Lock"
                        prepend-icon="mdi-lock"
                        :disabled="!['accepted', 'edited'].includes(candidate.review_status)"
                        @click="openReview(candidate, 'lock')"
                      />
                    </v-list>
                  </v-menu>
                </td>
              </tr>
            </tbody>
          </v-table>
        </v-card-text>
        <v-card-actions class="px-4 pb-4">
          <v-btn
            v-if="group.parameterFamily === 'execution_duration_seconds'"
            size="small"
            variant="tonal"
            prepend-icon="mdi-database-search-outline"
            @click="openHistoricalSearch(group.entityId)"
          >
            Try historical evidence
          </v-btn>
          <v-btn
            size="small"
            variant="text"
            prepend-icon="mdi-account-edit-outline"
            @click="openReview(group.candidates.find(isActive) ?? group.candidates[0], 'edit')"
          >
            Add expert value
          </v-btn>
        </v-card-actions>
      </v-card>
    </template>

    <v-expansion-panels class="mt-6" variant="accordion">
      <v-expansion-panel>
        <v-expansion-panel-title>Attach completed expert-survey references</v-expansion-panel-title>
        <v-expansion-panel-text>
          <p class="text-body-2 text-medium-emphasis mb-4">
            Upload the compact CSV exported from the completed expert survey. Matching references measure candidate fidelity; they never overwrite the executable baseline or replace an expert edit.
          </p>
          <v-file-input
            v-model="expertReferenceFiles"
            label="Expert-survey reference CSV"
            accept="text/csv,.csv"
            prepend-icon="mdi-clipboard-check-outline"
          />
          <v-btn color="primary" :loading="importingExpertReferences" :disabled="!expertReferenceFiles.length" @click="importExpertSurveyReferences">
            Attach expert-survey references
          </v-btn>
          <v-alert v-if="expertReferenceMessage" type="success" variant="tonal" density="compact" class="mt-3">
            {{ expertReferenceMessage }}
          </v-alert>
        </v-expansion-panel-text>
      </v-expansion-panel>
      <v-expansion-panel>
        <v-expansion-panel-title>Advanced candidate import</v-expansion-panel-title>
        <v-expansion-panel-text>
          <p class="text-body-2 text-medium-emphasis mb-4">
            Import or discover a frozen research candidate package only when you need externally prepared alternatives. Exact baseline-hash matching protects the executable configuration.
          </p>
          <v-btn
            color="primary"
            variant="tonal"
            prepend-icon="mdi-database-search-outline"
            :loading="discovering"
            class="mb-4"
            @click="autoAttachCandidates"
          >
            Find compatible research package
          </v-btn>
          <v-file-input
            v-model="importFiles"
            label="Candidate-set JSON"
            accept="application/json,.json"
            prepend-icon="mdi-file-upload-outline"
          />
          <v-btn color="primary" :loading="importing" :disabled="!importFiles.length" @click="importCandidates">
            Import candidate set
          </v-btn>
        </v-expansion-panel-text>
      </v-expansion-panel>
    </v-expansion-panels>

    <v-dialog v-model="reviewDialog" max-width="680">
      <v-card>
        <v-card-item>
          <v-card-title>{{ humanize(selectedAction) }} parameter candidate</v-card-title>
          <v-card-subtitle>{{ selectedCandidate?.entity_name || selectedCandidate?.entity_id }}</v-card-subtitle>
        </v-card-item>
        <v-card-text>
          <v-text-field
            v-model="reviewerId"
            label="Reviewer identifier"
            hint="Use a stable organizational identifier or research pseudonym."
            persistent-hint
            class="mb-3"
          />
          <v-textarea
            v-if="selectedAction === 'edit'"
            v-model="replacementValue"
            label="Replacement value"
            hint="Enter a number for a scalar, or a complete distribution JSON object."
            persistent-hint
            rows="6"
            class="mb-3"
          />
          <v-textarea
            v-model="justification"
            label="Required justification"
            hint="Explain the operational knowledge or evidence behind this decision."
            persistent-hint
            rows="4"
          />
          <v-alert v-if="dialogError" type="error" variant="tonal" density="compact" class="mt-3">
            {{ dialogError }}
          </v-alert>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="reviewDialog = false">Cancel</v-btn>
          <v-btn color="primary" :loading="submitting" @click="submitReview">
            Record {{ selectedAction }}
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-dialog v-model="applicationDialog" max-width="640">
      <v-card>
        <v-card-item>
          <v-card-title>Use candidate in baseline</v-card-title>
          <v-card-subtitle>
            {{ applicationCandidate?.entity_name || applicationCandidate?.entity_id }} · {{ humanize(applicationCandidate?.method) }}
          </v-card-subtitle>
        </v-card-item>
        <v-card-text>
          <v-alert type="warning" variant="tonal" class="mb-4">
            This changes the executable baseline. Existing simulation results will be marked stale until you rerun the simulation.
          </v-alert>
          <v-text-field v-model="applicationReviewerId" label="Reviewer identifier" class="mb-3" />
          <v-textarea
            v-model="applicationJustification"
            label="Selection reason"
            hint="Explain why this evidence source and value should drive the simulation."
            persistent-hint
            rows="4"
          />
          <v-alert v-if="applicationError" type="error" variant="tonal" density="compact" class="mt-3">
            {{ applicationError }}
          </v-alert>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="applicationDialog = false">Cancel</v-btn>
          <v-btn color="primary" :loading="applying" @click="applyCandidate">Use in baseline</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-dialog v-model="hybridDialog" max-width="680">
      <v-card>
        <v-card-item>
          <v-card-title>Freeze selected configuration</v-card-title>
          <v-card-subtitle>Save the active candidate mixture with an executable parameter snapshot.</v-card-subtitle>
        </v-card-item>
        <v-card-text>
          <v-alert type="info" variant="tonal" class="mb-4">
            {{ activeCandidateIds.length }} selected candidate{{ activeCandidateIds.length === 1 ? '' : 's' }} will be recorded. Parameters without a selected candidate remain explicit baseline assumptions.
          </v-alert>
          <v-text-field v-model="hybridName" label="Configuration name" class="mb-3" />
          <v-text-field v-model="hybridReviewerId" label="Reviewer identifier" class="mb-3" />
          <v-textarea
            v-model="hybridJustification"
            label="Configuration rationale"
            rows="4"
            hint="Explain why this combination should be retained or evaluated."
            persistent-hint
          />
          <v-alert v-if="hybridError" type="error" variant="tonal" density="compact" class="mt-3">
            {{ hybridError }}
          </v-alert>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="hybridDialog = false">Cancel</v-btn>
          <v-btn color="primary" :loading="freezingHybrid" @click="freezeHybridConfiguration">
            Freeze and download
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-dialog v-model="historicalDialog" max-width="960">
      <v-card>
        <v-card-item>
          <v-card-title>Find similar historical tasks</v-card-title>
          <v-card-subtitle>{{ historicalResult?.target?.task_name || historicalTaskId }}</v-card-subtitle>
        </v-card-item>
        <v-card-text>
          <div v-if="historicalLoading" class="text-center py-10">
            <v-progress-circular indeterminate color="primary" />
          </div>
          <template v-else-if="historicalResult">
            <v-alert
              :type="historicalResult.sufficient ? 'success' : 'warning'"
              variant="tonal"
              class="mb-4"
            >
              <template v-if="historicalResult.sufficient">
                The frozen evidence rules are satisfied: {{ historicalResult.matches.length }} tasks,
                {{ historicalResult.process_families }} process families, and
                {{ historicalResult.combined_executions.toLocaleString() }} calibration observations.
              </template>
              <template v-else>
                Insufficient analogue evidence. AureaSim will not lower the thresholds or create a candidate.
                Required: at least {{ historicalResult.requirements.minimum_analogue_tasks }} tasks from
                {{ historicalResult.requirements.minimum_process_families }} process families and
                {{ historicalResult.requirements.minimum_combined_executions }} observations, each scoring at least
                {{ Math.round(historicalResult.requirements.minimum_score * 100) }}%.
              </template>
            </v-alert>
            <v-table density="comfortable" v-if="historicalResult.matches.length">
              <thead>
                <tr>
                  <th>Historical task</th><th>Process</th><th>Observations</th>
                  <th>Semantic</th><th>BPMN</th><th>Role</th><th>Domain</th><th>Total</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="match in historicalResult.matches" :key="`${match.process_alias}:${match.task_id}`">
                  <td class="font-weight-medium">{{ match.task_name }}</td>
                  <td>{{ match.process_alias }}</td>
                  <td>{{ Number(match.observation_count).toLocaleString() }}</td>
                  <td>{{ percent(match.semantic) }}</td>
                  <td>{{ percent(match.bpmn_context) }}</td>
                  <td>{{ percent(match.role) }}</td>
                  <td>{{ percent(match.domain) }}</td>
                  <td><v-chip size="small" color="primary" variant="tonal">{{ percent(match.score) }}</v-chip></td>
                </tr>
              </tbody>
            </v-table>
            <p v-else class="text-body-2 text-medium-emphasis mb-0">
              No task in the repository reached the frozen {{ Math.round(historicalResult.requirements.minimum_score * 100) }}% similarity threshold.
            </p>
          </template>
          <v-alert v-if="historicalError" type="error" variant="tonal">{{ historicalError }}</v-alert>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="historicalDialog = false">Close</v-btn>
          <v-btn
            color="primary"
            :disabled="!historicalResult?.sufficient"
            :loading="historicalCreating"
            @click="createHistoricalCandidate"
          >
            Add duration candidate
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'

const props = defineProps<{ projectName: string }>()
const emit = defineEmits<{
  baselineUpdated: [payload: any]
  candidateAvailability: [keys: string[]]
}>()

const loading = ref(true)
const error = ref('')
const available = ref(false)
const candidates = ref<any[]>([])
const reviewQueue = ref<any[]>([])
const auditEventCount = ref(0)
const auditChainValid = ref(true)
const activeCandidateIds = ref<string[]>([])
const validationState = ref<any>({ status: 'not_validated', current: false, report: null })
const validationRunning = ref(false)
const validationError = ref('')

const reviewDialog = ref(false)
const selectedCandidate = ref<any | null>(null)
const selectedAction = ref('accept')
const reviewerId = ref('')
const justification = ref('')
const replacementValue = ref('')
const dialogError = ref('')
const submitting = ref(false)
const importFiles = ref<File[]>([])
const importing = ref(false)
const expertReferenceFiles = ref<File[]>([])
const importingExpertReferences = ref(false)
const expertReferenceMessage = ref('')
const discovering = ref(false)
const applicationDialog = ref(false)
const applicationCandidate = ref<any | null>(null)
const applicationReviewerId = ref('local-user')
const applicationJustification = ref('')
const applicationError = ref('')
const applying = ref(false)
const focusedGroupKey = ref('')
const hybridDialog = ref(false)
const hybridName = ref('Selected baseline')
const hybridReviewerId = ref('local-user')
const hybridJustification = ref('')
const hybridError = ref('')
const freezingHybrid = ref(false)
const historicalDialog = ref(false)
const historicalTaskId = ref('')
const historicalResult = ref<any | null>(null)
const historicalLoading = ref(false)
const historicalCreating = ref(false)
const historicalError = ref('')

const candidateGroups = computed(() => {
  const groups = new Map<string, any>()
  for (const candidate of candidates.value) {
    const key = `${candidate.parameter_family}::${candidate.entity_id}`
    if (!groups.has(key)) {
      groups.set(key, {
        key,
        parameterFamily: candidate.parameter_family,
        entityId: candidate.entity_id,
        entityName: candidate.entity_name || candidate.entity_id,
        candidates: [],
      })
    }
    groups.get(key).candidates.push(candidate)
  }
  return Array.from(groups.values()).sort((left, right) =>
    `${left.parameterFamily}:${left.entityName}`.localeCompare(`${right.parameterFamily}:${right.entityName}`),
  )
})

const validationAlertType = computed<'success' | 'error' | 'warning' | 'info'>(() => ({
  valid: 'success', invalid: 'error', stale: 'warning', not_validated: 'info', unreadable: 'error',
} as Record<string, 'success' | 'error' | 'warning' | 'info'>)[validationState.value?.status] ?? 'info')

const validationLabel = computed(() => ({
  valid: 'The current executable baseline is valid.',
  invalid: 'The baseline is invalid and cannot be frozen.',
  stale: 'The baseline changed after its last validation.',
  not_validated: 'The baseline has not yet been validated.',
  unreadable: 'The saved validation report is unreadable.',
} as Record<string, string>)[validationState.value?.status] ?? 'Validation state is unknown.')

function humanize(value: string | undefined): string {
  if (!value) return ''
  return value.replace(/_/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase())
}

function confidenceColor(value: string): string {
  return ({ high: 'success', medium: 'warning', low: 'error', unknown: 'grey' } as Record<string, string>)[value] ?? 'grey'
}

function statusColor(value: string): string {
  return ({ accepted: 'success', edited: 'info', rejected: 'error', locked: 'primary', pending: 'warning' } as Record<string, string>)[value] ?? 'grey'
}

function statusCount(status: string): number {
  return candidates.value.filter(candidate => candidate.review_status === status).length
}

function formatCandidateValue(candidate: any): string {
  if (candidate.scalar_value !== null && candidate.scalar_value !== undefined) {
    return `${Number(candidate.scalar_value).toLocaleString()} ${candidate.unit}`
  }
  const distribution = candidate.distribution
  if (!distribution) return 'No value'
  const quantiles = distribution.empirical_quantiles ?? {}
  if (quantiles.p50 !== undefined) return `${humanize(distribution.distribution_name)} · p50 ${Number(quantiles.p50).toLocaleString()} ${candidate.unit}`
  return `${humanize(distribution.distribution_name)} · ${distribution.distribution_params?.join(', ') ?? ''}`
}

function formatErrorPercent(value: unknown): string {
  const percent = Number(value) * 100
  if (!Number.isFinite(percent)) return 'unknown'
  if (percent >= 10000) return `${Math.round(percent).toLocaleString()}%`
  if (percent >= 100) return `${percent.toFixed(0)}%`
  return `${percent.toFixed(1)}%`
}

function expectedErrorRange(candidate: any): string {
  const profile = candidate.reliability_profile
  const expected = candidate.expected_error
  const p10 = profile?.expected_error_p10 ?? expected?.p10
  const median = profile?.expected_error_median ?? expected?.median
  const p90 = profile?.expected_error_p90 ?? expected?.p90
  if ([p10, median, p90].some(value => value === undefined || value === null)) {
    return median === undefined || median === null
      ? 'No empirical error range'
      : `Median ${formatErrorPercent(median)}`
  }
  return `p10 ${formatErrorPercent(p10)} · median ${formatErrorPercent(median)} · p90 ${formatErrorPercent(p90)}`
}

function reliabilityContext(candidate: any): string {
  const profile = candidate.reliability_profile
  if (!profile) return 'No matching research profile'
  return `${humanize(profile.reference_context)} · n=${profile.independent_units}`
}

function evidenceSource(candidate: any): string {
  const source = candidate.evidence?.[0]?.source
  if (!source) return 'Source unavailable'
  return source.replace('AutoGenerated_Base_params.json#', 'Generated baseline · ')
}

function evidenceSummary(candidate: any): string {
  const evidence = candidate.evidence ?? []
  const notes = evidence[0]?.notes || candidate.confidence_basis || ''
  const suffix = evidence.length > 1 ? ` · +${evidence.length - 1} source${evidence.length === 2 ? '' : 's'}` : ''
  const summary = `${notes}${suffix}`
  return summary.length > 180 ? `${summary.slice(0, 177)}…` : summary
}

function measuredFidelity(candidate: any): string {
  if (!candidate.measured_fidelity) return 'Not measured'
  const value = candidate.measured_fidelity.relative_error ?? candidate.measured_fidelity.median
  return value === undefined ? 'Measured reference available' : `${(Number(value) * 100).toFixed(1)}% error`
}

function fidelityReference(candidate: any): string {
  const fidelity = candidate.measured_fidelity
  if (!fidelity) return ''
  const type = fidelity.reference_type === 'expert_survey_reference'
    ? 'Expert-survey reference'
    : fidelity.reference_type === 'operational_reference'
      ? 'Operational reference'
      : 'Independent reference'
  return fidelity.source ? `${type} · ${fidelity.source}` : type
}

async function importExpertSurveyReferences() {
  const file = expertReferenceFiles.value[0]
  if (!file) return
  importingExpertReferences.value = true
  expertReferenceMessage.value = ''
  error.value = ''
  try {
    const form = new FormData()
    form.append('reference_file', file)
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/parameter-candidates/expert-survey-reference`,
      { method: 'POST', body: form },
    )
    const data = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`)
    expertReferenceMessage.value = `${data.matched_candidates} candidate${data.matched_candidates === 1 ? '' : 's'} matched to expert-survey references.`
    expertReferenceFiles.value = []
    await fetchCandidates()
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : 'Could not attach expert-survey references.'
  } finally {
    importingExpertReferences.value = false
  }
}

async function fetchCandidates() {
  loading.value = true
  error.value = ''
  try {
    const response = await fetch(`/api/projects/${encodeURIComponent(props.projectName)}/parameter-candidates`)
    if (!response.ok) {
      const body = await response.json().catch(() => ({}))
      throw new Error(body.detail || `HTTP ${response.status}`)
    }
    let data = await response.json()
    if (!data.available) {
      const initialized = await fetch(
        `/api/projects/${encodeURIComponent(props.projectName)}/parameter-candidates/initialize`,
        { method: 'POST' },
      )
      const initializedBody = await initialized.json().catch(() => ({}))
      if (!initialized.ok) throw new Error(initializedBody.detail || `HTTP ${initialized.status}`)
      const refreshed = await fetch(`/api/projects/${encodeURIComponent(props.projectName)}/parameter-candidates`)
      if (!refreshed.ok) {
        const body = await refreshed.json().catch(() => ({}))
        throw new Error(body.detail || `HTTP ${refreshed.status}`)
      }
      data = await refreshed.json()
    }
    available.value = data.available
    candidates.value = data.candidate_set?.candidates ?? []
    reviewQueue.value = data.review_queue ?? []
    auditEventCount.value = data.audit_event_count ?? 0
    auditChainValid.value = data.audit_chain_valid !== false
    activeCandidateIds.value = data.active_candidate_ids ?? []
    emit('candidateAvailability', candidates.value.map(candidateKey))
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : 'Could not load parameter candidates.'
  } finally {
    loading.value = false
  }
}

async function fetchValidation() {
  validationError.value = ''
  try {
    const response = await fetch(`/api/projects/${encodeURIComponent(props.projectName)}/baseline-validation`)
    const data = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`)
    validationState.value = data
  } catch (reason) {
    validationError.value = reason instanceof Error ? reason.message : 'Could not read validation state.'
  }
}

async function runValidation() {
  validationRunning.value = true
  validationError.value = ''
  try {
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/baseline-validation`,
      { method: 'POST' },
    )
    const data = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`)
    validationState.value = data
  } catch (reason) {
    validationError.value = reason instanceof Error ? reason.message : 'Could not validate the baseline.'
  } finally {
    validationRunning.value = false
  }
}

function candidateKey(candidate: any): string {
  return `${candidate.parameter_family}::${candidate.entity_id}`
}

function groupElementId(key: string): string {
  return `candidate-group-${key.replace(/[^a-zA-Z0-9_-]/g, '-')}`
}

function openParameter(parameterFamily: string, entityId: string): boolean {
  const key = `${parameterFamily}::${entityId}`
  if (!candidateGroups.value.some(group => group.key === key)) return false
  focusedGroupKey.value = key
  nextTick(() => {
    document.getElementById(groupElementId(key))?.scrollIntoView({ behavior: 'smooth', block: 'center' })
  })
  return true
}

async function openHistoricalSearch(taskId: string) {
  historicalTaskId.value = taskId
  historicalResult.value = null
  historicalError.value = ''
  historicalDialog.value = true
  historicalLoading.value = true
  try {
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/historical-analogues/${encodeURIComponent(taskId)}`,
    )
    const data = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`)
    historicalResult.value = data
  } catch (reason) {
    historicalError.value = reason instanceof Error ? reason.message : 'Could not search historical tasks.'
  } finally {
    historicalLoading.value = false
  }
}

defineExpose({ openParameter, openHistoricalSearch, refreshValidation: fetchValidation })

function percent(value: number): string {
  return `${(Number(value) * 100).toFixed(0)}%`
}

async function createHistoricalCandidate() {
  historicalCreating.value = true
  historicalError.value = ''
  try {
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/historical-analogues/${encodeURIComponent(historicalTaskId.value)}/candidate`,
      { method: 'POST' },
    )
    const data = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`)
    historicalDialog.value = false
    await fetchCandidates()
  } catch (reason) {
    historicalError.value = reason instanceof Error ? reason.message : 'Could not create the historical candidate.'
  } finally {
    historicalCreating.value = false
  }
}

function isExecutable(candidate: any): boolean {
  return [
    'execution_duration_seconds', 'interarrival_time_seconds',
    'resource_cost_per_hour', 'resource_capacity', 'gateway_probability',
  ].includes(candidate.parameter_family)
    && candidate.validity === 'valid'
}

function isActive(candidate: any): boolean {
  return activeCandidateIds.value.includes(candidate.candidate_id)
}

function openApplication(candidate: any) {
  applicationCandidate.value = candidate
  applicationJustification.value = ''
  applicationError.value = ''
  applicationDialog.value = true
}

function openHybridDialog() {
  hybridJustification.value = ''
  hybridError.value = ''
  hybridDialog.value = true
}

async function freezeHybridConfiguration() {
  hybridError.value = ''
  if (!hybridName.value.trim() || !hybridReviewerId.value.trim() || hybridJustification.value.trim().length < 8) {
    hybridError.value = 'Name, reviewer identifier, and a rationale of at least eight characters are required.'
    return
  }
  freezingHybrid.value = true
  try {
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/hybrid-configurations`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: hybridName.value.trim(),
          reviewer_id: hybridReviewerId.value.trim(),
          justification: hybridJustification.value.trim(),
          explicit_assumptions: {},
        }),
      },
    )
    const data = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`)
    hybridDialog.value = false
    const link = document.createElement('a')
    link.href = data.download_url
    link.download = ''
    document.body.appendChild(link)
    link.click()
    link.remove()
  } catch (reason) {
    hybridError.value = reason instanceof Error ? reason.message : 'Could not freeze this configuration.'
  } finally {
    freezingHybrid.value = false
  }
}

async function applyCandidate() {
  applicationError.value = ''
  if (!applicationReviewerId.value.trim() || applicationJustification.value.trim().length < 8) {
    applicationError.value = 'Reviewer identifier and a selection reason of at least eight characters are required.'
    return
  }
  applying.value = true
  try {
    const identifier = encodeURIComponent(applicationCandidate.value.candidate_id)
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/parameter-candidates/${identifier}/apply`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          reviewer_id: applicationReviewerId.value.trim(),
          justification: applicationJustification.value.trim(),
        }),
      },
    )
    if (!response.ok) {
      const data = await response.json().catch(() => ({}))
      throw new Error(data.detail || `HTTP ${response.status}`)
    }
    const data = await response.json()
    activeCandidateIds.value = data.active_candidate_ids ?? []
    applicationDialog.value = false
    emit('baselineUpdated', data)
    await fetchValidation()
  } catch (reason) {
    applicationError.value = reason instanceof Error ? reason.message : 'Could not apply this candidate.'
  } finally {
    applying.value = false
  }
}

async function importCandidates() {
  if (!importFiles.value.length) return
  importing.value = true
  error.value = ''
  try {
    const text = await importFiles.value[0].text()
    const payload = JSON.parse(text)
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/parameter-candidates`,
      { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) },
    )
    if (!response.ok) {
      const body = await response.json().catch(() => ({}))
      throw new Error(body.detail || `HTTP ${response.status}`)
    }
    importFiles.value = []
    await fetchCandidates()
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : 'Could not import candidate package.'
  } finally {
    importing.value = false
  }
}

async function autoAttachCandidates() {
  discovering.value = true
  error.value = ''
  try {
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/parameter-candidates/auto-attach`,
      { method: 'POST' },
    )
    if (!response.ok) {
      const body = await response.json().catch(() => ({}))
      throw new Error(body.detail || `HTTP ${response.status}`)
    }
    await fetchCandidates()
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : 'Could not attach a compatible candidate package.'
  } finally {
    discovering.value = false
  }
}

function openReview(candidate: any, action: string) {
  selectedCandidate.value = candidate
  selectedAction.value = action
  justification.value = ''
  dialogError.value = ''
  replacementValue.value = action === 'edit'
    ? JSON.stringify(candidate.distribution ?? candidate.scalar_value, null, 2)
    : ''
  reviewDialog.value = true
}

async function submitReview() {
  dialogError.value = ''
  if (!reviewerId.value.trim() || justification.value.trim().length < 8) {
    dialogError.value = 'Reviewer identifier and a justification of at least eight characters are required.'
    return
  }
  const body: Record<string, any> = {
    action: selectedAction.value,
    reviewer_id: reviewerId.value.trim(),
    justification: justification.value.trim(),
  }
  if (selectedAction.value === 'edit') {
    try {
      const parsed = JSON.parse(replacementValue.value)
      if (typeof parsed === 'number') body.scalar_value = parsed
      else if (parsed && typeof parsed === 'object') body.distribution = parsed
      else throw new Error('Replacement must be a number or distribution object.')
    } catch (reason) {
      dialogError.value = reason instanceof Error ? reason.message : 'Replacement value is not valid JSON.'
      return
    }
  }
  submitting.value = true
  try {
    const identifier = encodeURIComponent(selectedCandidate.value.candidate_id)
    const response = await fetch(
      `/api/projects/${encodeURIComponent(props.projectName)}/parameter-candidates/${identifier}/review`,
      { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) },
    )
    if (!response.ok) {
      const data = await response.json().catch(() => ({}))
      throw new Error(data.detail || `HTTP ${response.status}`)
    }
    reviewDialog.value = false
    await fetchCandidates()
  } catch (reason) {
    dialogError.value = reason instanceof Error ? reason.message : 'Could not record the review decision.'
  } finally {
    submitting.value = false
  }
}

onMounted(() => {
  fetchCandidates()
  fetchValidation()
})
watch(() => props.projectName, () => {
  fetchCandidates()
  fetchValidation()
})
</script>
