import json
import os
from pathlib import Path

from fastapi.testclient import TestClient

import server


def test_baseline_parameter_edit_is_audited_and_marks_results_stale(tmp_path, monkeypatch):
    projects = tmp_path / "projects"
    project = projects / "demo"
    results = project / "results"
    results.mkdir(parents=True)
    (project / "demo.bpmn").write_text(
        '<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">'
        '<process id="p"><task id="Task_Install"/></process></definitions>',
        encoding="utf-8",
    )
    base_path = project / "AutoGenerated_Base_params.json"
    base_path.write_text(json.dumps({
        "metadata": {},
        "resource_profiles": [],
        "task_resource_distribution": [{
            "task_id": "Task_Install",
            "resources": [{
                "resource_id": "Installer_1",
                "distribution_name": "norm",
                "distribution_params": [
                    {"value": 3600}, {"value": 600}, {"value": 0}, {"value": 999999},
                ],
            }],
        }],
        "gateway_branching_probabilities": [],
    }), encoding="utf-8")
    kpi_path = results / "Simulation_KPIs.csv"
    kpi_path.write_text("Scenario,Total_Cases\nBase,1\n", encoding="utf-8")
    old = base_path.stat().st_mtime - 10
    os.utime(kpi_path, (old, old))

    monkeypatch.setattr(server, "PROJECTS_DIR", projects)
    client = TestClient(server.app)
    response = client.patch(
        "/api/projects/demo/baseline-parameters",
        json={
            "parameter_type": "task_duration",
            "entity_id": "Task_Install",
            "values": {"mean_minutes": 90, "stddev_minutes": 15},
            "justification": "Measured by the process owner.",
            "reviewer_id": "expert-01",
        },
    )
    assert response.status_code == 200
    assert response.json()["revision"] == 1
    assert response.json()["results_stale"] is True
    saved = json.loads(base_path.read_text(encoding="utf-8"))
    params = saved["task_resource_distribution"][0]["resources"][0]["distribution_params"]
    assert params[0]["value"] == 5400
    history = json.loads((project / "baseline_parameter_history.json").read_text(encoding="utf-8"))
    assert history[0]["reviewer_id"] == "expert-01"
    assert client.get("/api/projects/demo").json()["results_stale"] is True
