import hashlib
import json

from fastapi.testclient import TestClient

import server
from aureasim.expert_review import CandidateReviewLedger, save_review_files
from tests.test_expert_review import candidate_set


def test_auto_attach_and_hybrid_zip_export(tmp_path, monkeypatch):
    projects = tmp_path / "projects"
    project = projects / "demo"
    project.mkdir(parents=True)
    items = candidate_set()
    identifier = items.candidates[0].candidate_id
    base_path = project / "AutoGenerated_Base_params.json"
    base_path.write_text(json.dumps({
        "metadata": {},
        "task_resource_distribution": [{
            "task_id": "task",
            "resources": [{
                "resource_id": "worker_1",
                "candidate_id": identifier,
                "distribution_name": "lognorm",
                "distribution_params": [{"value": 1}, {"value": 0}, {"value": 10}],
            }],
        }],
    }), encoding="utf-8")
    (project / "baseline_validation.json").write_text(json.dumps({
        "format_version": 1,
        "status": "valid",
        "configuration_sha256": hashlib.sha256(base_path.read_bytes()).hexdigest(),
        "errors": [],
        "warnings": [],
        "smoke_simulation": {"status": "passed", "cases": 1},
    }), encoding="utf-8")
    items = items.model_copy(update={
        "base_configuration_sha256": hashlib.sha256(base_path.read_bytes()).hexdigest(),
    })
    catalog = tmp_path / "local_evidence" / "candidate_packages" / "P01"
    catalog.mkdir(parents=True)
    (catalog / "parameter_candidates.json").write_text(items.model_dump_json(indent=2), encoding="utf-8")
    monkeypatch.setattr(server, "PROJECTS_DIR", projects)
    monkeypatch.setattr(server, "BASE_DIR", tmp_path)
    client = TestClient(server.app)

    attached = client.post("/api/projects/demo/parameter-candidates/auto-attach")
    assert attached.status_code == 201
    assert attached.json()["candidates"] == 1
    frozen = client.post("/api/projects/demo/hybrid-configurations", json={
        "name": "Validation candidate",
        "reviewer_id": "expert-01",
        "justification": "Freeze this combination for validation.",
        "explicit_assumptions": {"calendar": "baseline assumption"},
    })
    assert frozen.status_code == 201
    download = client.get(frozen.json()["download_url"])
    assert download.status_code == 200
    assert download.headers["content-type"] == "application/zip"
    assert download.content.startswith(b"PK")
