import json
from pathlib import Path

from aureasim import executor
from aureasim.ai_generator import ExperimentScenarioSchema
import pytest


def test_resolve_prosimos_beside_active_python(monkeypatch, tmp_path):
    scripts_dir = tmp_path / "Scripts"
    scripts_dir.mkdir()
    python_exe = scripts_dir / "python.exe"
    prosimos_exe = scripts_dir / "prosimos.exe"
    python_exe.touch()
    prosimos_exe.touch()

    monkeypatch.delenv("PROSIMOS_BIN", raising=False)
    monkeypatch.setattr(executor.shutil, "which", lambda _name: None)
    monkeypatch.setattr(executor.sys, "executable", str(python_exe))
    monkeypatch.setattr(executor.os, "name", "nt")

    assert Path(executor._resolve_prosimos_bin()) == prosimos_exe


def test_resolve_prosimos_prefers_explicit_configuration(monkeypatch):
    monkeypatch.setenv("PROSIMOS_BIN", r"C:\\tools\\prosimos.exe")

    assert executor._resolve_prosimos_bin() == r"C:\\tools\\prosimos.exe"


def test_zero_resource_allocation_is_rejected_instead_of_silently_coerced():
    scenario = {
        "name": "Installer_Absence",
        "resource_allocations": {"Installer": 0},
    }
    base_config = {
        "resource_profiles": [{"id": "Installer", "resource_list": []}],
    }

    with pytest.raises(ValueError, match="allocates 0 resources"):
        executor._validate_scenario_resource_allocations(scenario, base_config)


def test_unknown_resource_profile_allocation_is_rejected():
    scenario = {
        "name": "Typo",
        "resource_allocations": {"Instaler": 1},
    }
    base_config = {
        "resource_profiles": [{"id": "Installer", "resource_list": []}],
    }

    with pytest.raises(ValueError, match="unknown resource profile 'Instaler'"):
        executor._validate_scenario_resource_allocations(scenario, base_config)


def test_legacy_role_id_punctuation_and_case_are_resolved():
    scenario = {
        "name": "Legacy",
        "resource_allocations": {"Eco_Advisor": 2},
    }
    base_config = {
        "resource_profiles": [{"id": "eco_Advisor", "resource_list": []}],
    }

    assert executor._validate_scenario_resource_allocations(scenario, base_config) == {
        "eco_Advisor": 2,
    }


def test_bundled_demo_scenarios_have_feasible_resource_allocations():
    """Every fixed offline demo must be executable without an AI service."""
    examples_dir = Path(__file__).resolve().parents[1] / "examples"
    for config_path in examples_dir.glob("*_config.json"):
        process_name = config_path.name.removesuffix("_config.json")
        base_path = examples_dir / f"{process_name}_base.json"
        config = json.loads(config_path.read_text(encoding="utf-8"))
        base = json.loads(base_path.read_text(encoding="utf-8"))
        for scenario in config["scenarios"]:
            executor._validate_scenario_resource_allocations(scenario, base)


def test_published_gallery_scenarios_have_feasible_resource_allocations():
    """The three distributed gallery projects must not contain zero staffing."""
    software_dir = Path(__file__).resolve().parents[1]
    for project_name in ("Incident Management", "Leave Request", "RES_Sales_Process"):
        project_dir = software_dir / "projects" / project_name
        config = json.loads(
            (project_dir / "AutoGenerated_Experiment_Scenarios.json").read_text(encoding="utf-8")
        )
        base = json.loads(
            (project_dir / "AutoGenerated_Base_params.json").read_text(encoding="utf-8")
        )
        for scenario in config["scenarios"]:
            executor._validate_scenario_resource_allocations(scenario, base)


def test_generated_scenario_schema_rejects_zero_resource_allocation():
    with pytest.raises(ValueError, match="greater than or equal to 1"):
        ExperimentScenarioSchema.model_validate({
            "metadata": {
                "methodology": "stress test",
                "sources": [],
                "source_urls": [],
                "rationale": "test",
            },
            "base_parameters": "",
            "report_settings": {
                "title": "test",
                "description": "test",
                "kpis": {"wait_times": []},
            },
            "scenarios": [{
                "name": "A_Baseline",
                "description": "test",
                "arrival_rate": 144000,
                "resource_allocations_list": [{"role_id": "Role", "count": 0}],
            }],
        })
