import json

from aureasim.baseline_validation import validate_and_smoke, validation_state


def project_files(tmp_path):
    (tmp_path / "model.bpmn").write_text(
        '<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">'
        '<process id="p"><task id="task"/></process></definitions>',
        encoding="utf-8",
    )
    base = {
        "arrival_time_distribution": {
            "distribution_name": "expon",
            "distribution_params": [{"value": 0}, {"value": 60}, {"value": 0}, {"value": 9999}],
        },
        "resource_calendars": [{"id": "work", "time_periods": []}],
        "resource_profiles": [{
            "id": "workers",
            "resource_list": [{"id": "worker_1", "amount": 1, "calendar": "work"}],
        }],
        "task_resource_distribution": [{
            "task_id": "task",
            "resources": [{
                "resource_id": "worker_1",
                "distribution_name": "norm",
                "distribution_params": [
                    {"value": 60}, {"value": 10}, {"value": 0}, {"value": 9999},
                ],
            }],
        }],
        "gateway_branching_probabilities": [],
    }
    path = tmp_path / "AutoGenerated_Base_params.json"
    path.write_text(json.dumps(base), encoding="utf-8")
    return path


def test_validation_runs_one_case_smoke_and_becomes_stale_after_change(tmp_path):
    base_path = project_files(tmp_path)

    def runner(_bpmn, _params, log_path):
        log_path.write_text("case_id,activity\n1,task\n", encoding="utf-8")

    report = validate_and_smoke(project_path=tmp_path, runner=runner)
    assert report["status"] == "valid"
    assert report["smoke_simulation"]["status"] == "passed"
    assert validation_state(tmp_path)["status"] == "valid"
    base_path.write_text(base_path.read_text(encoding="utf-8") + "\n", encoding="utf-8")
    assert validation_state(tmp_path)["status"] == "stale"


def test_validation_rejects_unknown_resource_before_smoke(tmp_path):
    base_path = project_files(tmp_path)
    data = json.loads(base_path.read_text(encoding="utf-8"))
    data["task_resource_distribution"][0]["resources"][0]["resource_id"] = "missing"
    base_path.write_text(json.dumps(data), encoding="utf-8")
    report = validate_and_smoke(project_path=tmp_path)
    assert report["status"] == "invalid"
    assert report["smoke_simulation"]["status"] == "not_run"
    assert any("unknown resource missing" in error for error in report["errors"])
