import json

from fastapi.testclient import TestClient

import server
from aureasim.baseline_candidates import candidate_set_from_baseline


def baseline():
    return {
        "metadata": {
            "grounding_mode": "heuristic",
            "task_name_map": {"Task_Review": {"clean_task_name": "Review application"}},
        },
        "arrival_time_distribution": {
            "distribution_name": "expon",
            "distribution_params": [{"value": 0}, {"value": 3600}],
        },
        "resource_profiles": [{
            "id": "Reviewer", "name": "Reviewer",
            "resource_list": [{
                "id": "Reviewer_1", "cost_per_hour": 40, "amount": 2,
                "evidence_status": "grounded_confirmed",
                "evidence_rationale": "Published salary reference.",
            }],
        }],
        "task_resource_distribution": [{
            "task_id": "Task_Review",
            "resources": [{
                "resource_id": "Reviewer_1", "distribution_name": "norm",
                "distribution_params": [{"value": 600}, {"value": 120}],
                "evidence_status": "heuristic_fallback",
                "evidence_rationale": "Semantic task estimate.",
            }],
        }],
        "gateway_branching_probabilities": [{
            "gateway_id": "Gateway_1",
            "probabilities": [{"path_id": "Flow_yes", "value": 0.7}],
        }],
    }


def test_baseline_candidates_include_values_provenance_and_reliability(tmp_path):
    project = tmp_path / "demo"
    project.mkdir()
    (project / "AutoGenerated_Base_params.json").write_text(json.dumps(baseline()), encoding="utf-8")
    candidates = candidate_set_from_baseline(project)
    by_family = {item.parameter_family: item for item in candidates.candidates}
    duration = by_family["execution_duration_seconds"]
    assert duration.entity_name == "Review application"
    assert duration.application_status.value == "applied"
    assert duration.reliability_profile.expected_error_median == 0.9431890985720269
    assert duration.reliability_profile.expected_error_p90 == 11.181668427137163
    assert duration.evidence[0].source.startswith("AutoGenerated_Base_params.json#")
    cost = by_family["resource_cost_per_hour"]
    assert cost.method.value == "evidence_grounded"
    assert cost.reliability_profile.expected_error_p90 == 0.059
    assert {item.parameter_family for item in candidates.candidates} >= {
        "execution_duration_seconds", "interarrival_time_seconds",
        "resource_cost_per_hour", "resource_capacity", "gateway_probability",
    }


def test_initialize_endpoint_creates_candidates_and_marks_baseline_values_active(tmp_path, monkeypatch):
    projects = tmp_path / "projects"
    project = projects / "demo"
    project.mkdir(parents=True)
    (project / "AutoGenerated_Base_params.json").write_text(json.dumps(baseline()), encoding="utf-8")
    monkeypatch.setattr(server, "PROJECTS_DIR", projects)
    client = TestClient(server.app)
    initialized = client.post("/api/projects/demo/parameter-candidates/initialize")
    assert initialized.status_code == 201
    assert initialized.json()["candidates"] == 5
    fetched = client.get("/api/projects/demo/parameter-candidates").json()
    assert fetched["available"] is True
    assert len(fetched["active_candidate_ids"]) == 5
    assert (project / "parameter_candidates.json").exists()
