import json

from fastapi.testclient import TestClient

import server
from aureasim.expert_review import CandidateReviewLedger, save_review_files
from tests.test_expert_review import candidate_set


def test_candidate_application_updates_baseline_and_writes_selection_audit(tmp_path, monkeypatch):
    projects = tmp_path / "projects"
    project = projects / "demo"
    project.mkdir(parents=True)
    items = candidate_set()
    save_review_files(
        project / "parameter_candidates.json",
        project / "candidate_review_ledger.json",
        items,
        CandidateReviewLedger(candidate_set_id=items.candidate_set_id),
    )
    base_path = project / "AutoGenerated_Base_params.json"
    base_path.write_text(json.dumps({
        "metadata": {},
        "task_resource_distribution": [{
            "task_id": "task",
            "resources": [{
                "resource_id": "worker_1",
                "distribution_name": "norm",
                "distribution_params": [{"value": 60}, {"value": 10}],
            }],
        }],
    }), encoding="utf-8")

    monkeypatch.setattr(server, "PROJECTS_DIR", projects)
    client = TestClient(server.app)
    identifier = items.candidates[0].candidate_id
    response = client.post(
        f"/api/projects/demo/parameter-candidates/{identifier}/apply",
        json={
            "reviewer_id": "expert-01",
            "justification": "Selected because local operational evidence is strongest.",
        },
    )
    assert response.status_code == 200
    assert response.json()["active_candidate_ids"] == [identifier]
    saved = json.loads(base_path.read_text(encoding="utf-8"))
    assert saved["task_resource_distribution"][0]["resources"][0]["candidate_id"] == identifier
    history = json.loads((project / "parameter_selection_history.json").read_text(encoding="utf-8"))
    assert history[0]["candidate_id"] == identifier
    fetched = client.get("/api/projects/demo/parameter-candidates").json()
    assert fetched["active_candidate_ids"] == [identifier]
