import hashlib

from aureasim.candidate_catalog import discover_candidate_packages
from tests.test_expert_review import candidate_set


def test_catalog_reports_only_exact_baseline_compatibility(tmp_path):
    baseline = tmp_path / "AutoGenerated_Base_params.json"
    baseline.write_text("{}", encoding="utf-8")
    items = candidate_set().model_copy(update={
        "base_configuration_sha256": hashlib.sha256(baseline.read_bytes()).hexdigest(),
    })
    package = tmp_path / "local_evidence" / "candidate_packages" / "P01"
    package.mkdir(parents=True)
    (package / "parameter_candidates.json").write_text(
        items.model_dump_json(indent=2), encoding="utf-8"
    )
    results = discover_candidate_packages(tmp_path, baseline)
    assert len(results) == 1
    assert results[0]["compatible"] is True
    baseline.write_text('{"changed": true}', encoding="utf-8")
    assert discover_candidate_packages(tmp_path, baseline)[0]["compatible"] is False
