import json

from aureasim.hybrid_configuration import freeze_hybrid_configuration
from tests.test_expert_review import candidate_set


def test_freeze_hybrid_preserves_selection_and_executable_snapshot(tmp_path):
    items = candidate_set()
    identifier = items.candidates[0].candidate_id
    baseline = {
        "metadata": {},
        "task_resource_distribution": [{
            "task_id": "task",
            "resources": [{
                "resource_id": "worker_1",
                "candidate_id": identifier,
                "distribution_name": "lognorm",
                "distribution_params": [{"value": 1}, {"value": 0}, {"value": 10}],
            }],
        }],
    }
    (tmp_path / "AutoGenerated_Base_params.json").write_text(
        json.dumps(baseline), encoding="utf-8"
    )
    (tmp_path / "parameter_selection_history.json").write_text(json.dumps([{
        "candidate_id": identifier,
        "justification": "Direct local measurements are preferred.",
    }]), encoding="utf-8")
    hybrid, export_dir = freeze_hybrid_configuration(
        project_path=tmp_path,
        candidate_set=items,
        name="Operational candidate",
        reviewer_id="expert-01",
        justification="Freeze for the next validation run.",
    )
    assert hybrid.selections[0].candidate_id == identifier
    assert hybrid.selections[0].selection_reason == "Direct local measurements are preferred."
    assert (export_dir / "hybrid_selection.json").exists()
    assert json.loads((export_dir / "AutoGenerated_Base_params.json").read_text())["task_resource_distribution"]
