"""Freeze and export the currently selected mix of parameter candidates."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

from aureasim.candidate_application import selected_candidate_ids
from aureasim.parameter_candidates import (
    CandidateSelection,
    CandidateSet,
    HybridConfiguration,
    deterministic_candidate_id,
)


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def safe_export_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", value.strip()).strip("._")
    if not cleaned:
        raise ValueError("Configuration name must contain letters or numbers")
    return cleaned[:80]


def freeze_hybrid_configuration(
    *,
    project_path: Path,
    candidate_set: CandidateSet,
    name: str,
    reviewer_id: str,
    justification: str,
    explicit_assumptions: dict[str, str | float | int] | None = None,
) -> tuple[HybridConfiguration, Path]:
    base_path = project_path / "AutoGenerated_Base_params.json"
    baseline_bytes = base_path.read_bytes()
    baseline = json.loads(baseline_bytes)
    active_ids = selected_candidate_ids(baseline, candidate_set)
    if not active_ids:
        raise ValueError("Select at least one candidate before freezing a hybrid configuration")

    candidates = {item.candidate_id: item for item in candidate_set.candidates}
    missing = [identifier for identifier in active_ids if identifier not in candidates]
    if missing:
        raise ValueError(f"Active baseline references candidates outside this package: {', '.join(missing)}")

    history_path = project_path / "parameter_selection_history.json"
    history: list[dict[str, Any]] = []
    if history_path.exists():
        history = json.loads(history_path.read_text(encoding="utf-8"))
    reasons = {
        event.get("candidate_id"): event.get("justification", "Selected in the active baseline.")
        for event in history
    }
    selections = [
        CandidateSelection(
            parameter_family=candidates[identifier].parameter_family,
            entity_id=candidates[identifier].entity_id,
            candidate_id=identifier,
            selection_reason=str(reasons.get(identifier, justification)),
        )
        for identifier in active_ids
    ]
    export_name = safe_export_name(name)
    hybrid_id = deterministic_candidate_id(
        "hybrid", candidate_set.candidate_set_id, export_name, *active_ids, _sha256_bytes(baseline_bytes)
    ).replace("pc_", "hyb_", 1)
    assumptions: dict[str, str | float | int] = {
        "configuration_name": name.strip(),
        "frozen_by": reviewer_id,
        "selection_justification": justification,
        "unselected_parameters": "Retained from the active baseline configuration",
    }
    assumptions.update(explicit_assumptions or {})
    hybrid = HybridConfiguration(
        hybrid_configuration_id=hybrid_id,
        candidate_set_id=candidate_set.candidate_set_id,
        process_alias=candidate_set.process_alias,
        selections=selections,
        explicit_assumptions=assumptions,
        evaluation_status="selected_not_yet_revalidated",
        configuration_sha256=_sha256_bytes(baseline_bytes),
    )

    export_dir = project_path / "hybrid_configurations" / f"{export_name}__{hybrid_id}"
    export_dir.mkdir(parents=True, exist_ok=False)
    (export_dir / "hybrid_selection.json").write_text(
        hybrid.model_dump_json(indent=2) + "\n", encoding="utf-8"
    )
    (export_dir / "AutoGenerated_Base_params.json").write_bytes(baseline_bytes)
    return hybrid, export_dir
